export const LEGACY_NAME_MAP: Record<string, string> = {
  '1. FC Heidenheim': '1. FC Heidenheim 1846',
  '1899 Hoffenheim': 'TSG 1899 Hoffenheim',
  'Alaves': 'Deportivo Alavés',
  'Angers': 'Angers SCO',
  'Arsenal': 'Arsenal FC',
  'Aston Villa': 'Aston Villa FC',
  'Atalanta': 'Atalanta BC',
  'Atletico Madrid': 'Club Atlético de Madrid',
  'Auxerre': 'AJ Auxerre',
  'Barcelona': 'FC Barcelona',
  'Bayer Leverkusen': 'Bayer 04 Leverkusen',
  'Bayern München': 'FC Bayern München',
  'Bologna': 'Bologna FC 1909',
  'Bournemouth': 'AFC Bournemouth',
  'Brentford': 'Brentford FC',
  'Brighton': 'Brighton & Hove Albion FC',
  'Burnley': 'Burnley FC',
  'Cagliari': 'Cagliari Calcio',
  'Celta Vigo': 'RC Celta de Vigo',
  'Chelsea': 'Chelsea FC',
  'Como': 'Como 1907',
  'Crystal Palace': 'Crystal Palace FC',
  'Espanyol': 'RCD Espanyol de Barcelona',
  'Everton': 'Everton FC',
  'FC St. Pauli': 'FC St. Pauli 1910',
  'FSV Mainz 05': '1. FSV Mainz 05',
  'Fiorentina': 'ACF Fiorentina',
  'Fulham': 'Fulham FC',
  'Genoa': 'Genoa CFC',
  'Getafe': 'Getafe CF',
  'Girona': 'Girona FC',
  'Hellas Verona': 'Hellas Verona FC',
  'Inter': 'FC Internazionale Milano',
  'Juventus': 'Juventus FC',
  'Lazio': 'SS Lazio',
  'Le Havre': 'Le Havre AC',
  'Lecce': 'US Lecce',
  'Lens': 'Racing Club de Lens',
  'Levante': 'Levante UD',
  'Lille': 'Lille OSC',
  'Liverpool': 'Liverpool FC',
  'Lorient': 'FC Lorient',
  'Lyon': 'Olympique Lyonnais',
  'Mallorca': 'RCD Mallorca',
  'Manchester City': 'Manchester City FC',
  'Manchester United': 'Manchester United FC',
  'Marseille': 'Olympique de Marseille',
  'Metz': 'FC Metz',
  'Monaco': 'AS Monaco FC',
  'Nantes': 'FC Nantes',
  'Napoli': 'SSC Napoli',
  'Newcastle': 'Newcastle United FC',
  'Nice': 'OGC Nice',
  'Nottingham Forest': 'Nottingham Forest FC',
  'Osasuna': 'CA Osasuna',
  'Paris Saint Germain': 'Paris Saint-Germain FC',
  'Parma': 'Parma Calcio 1913',
  'Pisa': 'AC Pisa 1909',
  'Rayo Vallecano': 'Rayo Vallecano de Madrid',
  'Real Betis': 'Real Betis Balompié',
  'Real Madrid': 'Real Madrid CF',
  'Real Sociedad': 'Real Sociedad de Fútbol',
  'Rennes': 'Stade Rennais FC 1901',
  'Sassuolo': 'US Sassuolo Calcio',
  'Sevilla': 'Sevilla FC',
  'Strasbourg': 'RC Strasbourg Alsace',
  'Sunderland': 'Sunderland AFC',
  'Torino': 'Torino FC',
  'Tottenham': 'Tottenham Hotspur FC',
  'Toulouse': 'Toulouse FC',
  'Udinese': 'Udinese Calcio',
  'Union Berlin': '1. FC Union Berlin',
  'Valencia': 'Valencia CF',
  'Villarreal': 'Villarreal CF',
  'Werder Bremen': 'SV Werder Bremen',
  'West Ham': 'West Ham United FC',
  'Wolves': 'Wolverhampton Wanderers FC',
};
